# APPLICATION IDENTITY
spring.application.name=cart-service

# SERVER CONFIGURATION

# Random port (best with service discovery)
server.port=0

# EUREKA / SERVICE DISCOVERY

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# MONGODB CONFIGURATION (LOCAL)

spring.data.mongodb.uri=mongodb://localhost:27017/cartdb
spring.data.mongodb.auto-index-creation=true

# REDIS CONFIGURATION (FUTURE USE)
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=60000

# KAFKA CONFIGURATION (FUTURE USE)
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=cart-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

# FEIGN CONFIGURATION
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.loggerLevel=basic

# ACTUATOR CONFIGURATION
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

# LOGGING CONFIGURATION
logging.level.root=INFO
logging.level.com.ecommerce.cart_service=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# JACKSON CONFIGURATION
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC